### PR TITLE
Fix incorrect extraneous quoting (issues #34 and #37)

### PR DESCRIPTION
**Pull request by leovandriel**

### CODE REVIEW

**Comment by andersondias** [comment]
:+1:

**Comment by andersondias** [comment]
Hi, can you merge this pull request and generate a new version of the gem?

**Comment by leovandriel** [comment]
FIY: A couple of months ago tlconnor announced that he's not maintaining this gem anymore, see #34. He offered to transfer the repo to anyone interested...

**Comment by andersondias** [comment]
Oh! Thanks @leonardvandriel for the information and thank you @tlconnor for creating this gem ;)

**Pull request closed without merging**
