### PR TITLE
Postgres syntax of arrays is '#{1,2,3}' (in quotes). But they aren't add...

### PR DESCRIPTION
**Pull request by izzm**
... automaticly.

Rails 3.0.9 + pg 0.11.0

### CODE REVIEW

**Comment by jmccartie** [comment]
@izzm Why was this closed? I'm having this issue now and not sure how to fix it.

```
  SQL (0.6ms)  INSERT INTO "video_profiles" ("created_at", "description", "kinds", "name", "slug", "updated_at") VALUES ('2013-09-09 15:16:58.534904', 'Video profiles for mobile.', {"default"}, 'TEMP', 'temp', '2013-09-09 15:16:58.534904') RETURNING "id"
   (0.3ms)  ROLLBACK
ActiveRecord::StatementInvalid: PG::Error: ERROR:  syntax error at or near "{"
LINE 1: ...9 15:16:58.534904', 'Video profiles for mobile.', {"default"...
                                                             ^
: INSERT INTO "video_profiles" ("created_at", "description", "kinds", "name", "slug", "updated_at") VALUES ('2013-09-09 15:16:58.534904', 'Video profiles for mobile.', {"default"}, 'TEMP', 'temp', '2013-09-09 15:16:58.534904') RETURNING "id"
```

**Comment by izzm** [comment]
@jmccartie Can i see your migration with video_profiles table definition? Are you use HStore?

**Comment by jmccartie** [comment]
@izzm 

schema.rb

```
  create_table "video_profiles", :force => true do |t|
    t.string       "name"
    t.string       "slug"
    t.string       "description"
    t.datetime     "created_at",  :null => false
    t.datetime     "updated_at",  :null => false
    t.string_array "kinds"
  end
```

gemfile

```
gem 'activerecord-postgres-hstore'
gem "activerecord-postgres-array" # Must be loaded after hstore
```

Strangely, I can't replicate this locally -- it's only happening in our production environment. (Postgres 9.2.4 in both places). I've verified that gem versions and table definitions match in both places.

**Comment by izzm** [comment]
@jmccartie master branch (version 0.0.9) not contains my fix! We need @tlconnor help.

**Comment by jmccartie** [comment]
We've narrowed it down to an issue with prepared statements -- which we have turned off in production because we're using pg bouncer.

Investigating further...

**Comment by jmccartie** [comment]
Confirmed that your commit fixed our problem

**Pull request merged**
